[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read-write", path = "./deployment"}]

optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
bracket_spacing = true

[lint]
exclude_lints = ["asm-keccak256"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
